language: go

go:
  - 1.7

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

branches:
  only: master

before_install:
  - go get -v github.com/mitchellh/gox
  - go get -v github.com/tcnksm/ghr

script:
  - go test -v ./...

after_success:
  - gox -osarch "darwin/amd64 linux/386 linux/amd64 windows/386 windows/amd64" -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr --username alireza-ahmadi --token $GITHUB_TOKEN --replace --prerelease $(git tag -l --contains HEAD) dist/
